/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WellnessPlanRouteImport } from './routes/wellness-plan'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HubRouteImport } from './routes/hub'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompanionRouteImport } from './routes/companion'
import { Route as ChatHistoryRouteImport } from './routes/chat-history'
import { Route as AssessmentHistoryRouteImport } from './routes/assessment-history'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as HubSlugRouteImport } from './routes/hub_.$slug'
import { Route as AdminWellnessHubRouteImport } from './routes/admin.wellness-hub'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminRemindersRouteImport } from './routes/admin.reminders'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminMoodsRouteImport } from './routes/admin.moods'
import { Route as AdminContactMessagesRouteImport } from './routes/admin.contact-messages'
import { Route as AdminActivitiesRouteImport } from './routes/admin.activities'

const WellnessPlanRoute = WellnessPlanRouteImport.update({
  id: '/wellness-plan',
  path: '/wellness-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionRoute = CompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatHistoryRoute = ChatHistoryRouteImport.update({
  id: '/chat-history',
  path: '/chat-history',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentHistoryRoute = AssessmentHistoryRouteImport.update({
  id: '/assessment-history',
  path: '/assessment-history',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const HubSlugRoute = HubSlugRouteImport.update({
  id: '/hub_/$slug',
  path: '/hub/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWellnessHubRoute = AdminWellnessHubRouteImport.update({
  id: '/wellness-hub',
  path: '/wellness-hub',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRemindersRoute = AdminRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMoodsRoute = AdminMoodsRouteImport.update({
  id: '/moods',
  path: '/moods',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactMessagesRoute = AdminContactMessagesRouteImport.update({
  id: '/contact-messages',
  path: '/contact-messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivitiesRoute = AdminActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRouteWithChildren
  '/assessment': typeof AssessmentRoute
  '/assessment-history': typeof AssessmentHistoryRoute
  '/chat-history': typeof ChatHistoryRoute
  '/companion': typeof CompanionRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/hub': typeof HubRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/wellness-plan': typeof WellnessPlanRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/contact-messages': typeof AdminContactMessagesRoute
  '/admin/moods': typeof AdminMoodsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reminders': typeof AdminRemindersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wellness-hub': typeof AdminWellnessHubRoute
  '/hub/$slug': typeof HubSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/activities': typeof ActivitiesRoute
  '/assessment': typeof AssessmentRoute
  '/assessment-history': typeof AssessmentHistoryRoute
  '/chat-history': typeof ChatHistoryRoute
  '/companion': typeof CompanionRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/hub': typeof HubRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/wellness-plan': typeof WellnessPlanRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/contact-messages': typeof AdminContactMessagesRoute
  '/admin/moods': typeof AdminMoodsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reminders': typeof AdminRemindersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wellness-hub': typeof AdminWellnessHubRoute
  '/hub/$slug': typeof HubSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRouteWithChildren
  '/assessment': typeof AssessmentRoute
  '/assessment-history': typeof AssessmentHistoryRoute
  '/chat-history': typeof ChatHistoryRoute
  '/companion': typeof CompanionRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/hub': typeof HubRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/wellness-plan': typeof WellnessPlanRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/contact-messages': typeof AdminContactMessagesRoute
  '/admin/moods': typeof AdminMoodsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reminders': typeof AdminRemindersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wellness-hub': typeof AdminWellnessHubRoute
  '/hub_/$slug': typeof HubSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/activities'
    | '/admin'
    | '/assessment'
    | '/assessment-history'
    | '/chat-history'
    | '/companion'
    | '/contact'
    | '/dashboard'
    | '/hub'
    | '/login'
    | '/profile'
    | '/signup'
    | '/wellness-plan'
    | '/admin/activities'
    | '/admin/contact-messages'
    | '/admin/moods'
    | '/admin/profile'
    | '/admin/reminders'
    | '/admin/users'
    | '/admin/wellness-hub'
    | '/hub/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/activities'
    | '/assessment'
    | '/assessment-history'
    | '/chat-history'
    | '/companion'
    | '/contact'
    | '/dashboard'
    | '/hub'
    | '/login'
    | '/profile'
    | '/signup'
    | '/wellness-plan'
    | '/admin/activities'
    | '/admin/contact-messages'
    | '/admin/moods'
    | '/admin/profile'
    | '/admin/reminders'
    | '/admin/users'
    | '/admin/wellness-hub'
    | '/hub/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/activities'
    | '/admin'
    | '/assessment'
    | '/assessment-history'
    | '/chat-history'
    | '/companion'
    | '/contact'
    | '/dashboard'
    | '/hub'
    | '/login'
    | '/profile'
    | '/signup'
    | '/wellness-plan'
    | '/admin/activities'
    | '/admin/contact-messages'
    | '/admin/moods'
    | '/admin/profile'
    | '/admin/reminders'
    | '/admin/users'
    | '/admin/wellness-hub'
    | '/hub_/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AdminRoute: typeof AdminRouteWithChildren
  AssessmentRoute: typeof AssessmentRoute
  AssessmentHistoryRoute: typeof AssessmentHistoryRoute
  ChatHistoryRoute: typeof ChatHistoryRoute
  CompanionRoute: typeof CompanionRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  HubRoute: typeof HubRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  WellnessPlanRoute: typeof WellnessPlanRoute
  HubSlugRoute: typeof HubSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wellness-plan': {
      id: '/wellness-plan'
      path: '/wellness-plan'
      fullPath: '/wellness-plan'
      preLoaderRoute: typeof WellnessPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companion': {
      id: '/companion'
      path: '/companion'
      fullPath: '/companion'
      preLoaderRoute: typeof CompanionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-history': {
      id: '/chat-history'
      path: '/chat-history'
      fullPath: '/chat-history'
      preLoaderRoute: typeof ChatHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment-history': {
      id: '/assessment-history'
      path: '/assessment-history'
      fullPath: '/assessment-history'
      preLoaderRoute: typeof AssessmentHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/hub_/$slug': {
      id: '/hub_/$slug'
      path: '/hub/$slug'
      fullPath: '/hub/$slug'
      preLoaderRoute: typeof HubSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wellness-hub': {
      id: '/admin/wellness-hub'
      path: '/wellness-hub'
      fullPath: '/admin/wellness-hub'
      preLoaderRoute: typeof AdminWellnessHubRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reminders': {
      id: '/admin/reminders'
      path: '/reminders'
      fullPath: '/admin/reminders'
      preLoaderRoute: typeof AdminRemindersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moods': {
      id: '/admin/moods'
      path: '/moods'
      fullPath: '/admin/moods'
      preLoaderRoute: typeof AdminMoodsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact-messages': {
      id: '/admin/contact-messages'
      path: '/contact-messages'
      fullPath: '/admin/contact-messages'
      preLoaderRoute: typeof AdminContactMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activities': {
      id: '/admin/activities'
      path: '/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AdminActivitiesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminActivitiesRoute: typeof AdminActivitiesRoute
  AdminContactMessagesRoute: typeof AdminContactMessagesRoute
  AdminMoodsRoute: typeof AdminMoodsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminRemindersRoute: typeof AdminRemindersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWellnessHubRoute: typeof AdminWellnessHubRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivitiesRoute: AdminActivitiesRoute,
  AdminContactMessagesRoute: AdminContactMessagesRoute,
  AdminMoodsRoute: AdminMoodsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminRemindersRoute: AdminRemindersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWellnessHubRoute: AdminWellnessHubRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  ActivitiesRoute: ActivitiesRoute,
  AdminRoute: AdminRouteWithChildren,
  AssessmentRoute: AssessmentRoute,
  AssessmentHistoryRoute: AssessmentHistoryRoute,
  ChatHistoryRoute: ChatHistoryRoute,
  CompanionRoute: CompanionRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  HubRoute: HubRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  WellnessPlanRoute: WellnessPlanRoute,
  HubSlugRoute: HubSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
